### ISSUE TITLE
Practica Animación Objeto 3D

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-equipo-balam#1]
[Animación Yakuin.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-equipo-balam/files/11579654/Animacion.Yakuin.pdf)

**Comment by josealfredo79** [comment]
Calificacion 19
